apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    application: health-pinger
  name: health-pinger
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        application: health-pinger
    spec:
      containers:
        - name: health-pinger
          image: stekarabdevregistry.azurecr.io/health-pinger:v1
          env:
            - name: ASPNETCORE_KUBERNETES
              value: "true"
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: health-pinger
  name: health-pinger-service
spec:
  type: LoadBalancer
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    application: health-pinger
status:
  loadBalancer: {}
