apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    application: healththree
  name: healththree
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        application: healththree
    spec:
      containers:
        - name: healththree
          image: stekarabdevregistry.azurecr.io/healththree:v1
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: healththree
  name: healththree-service
spec:
  ports:
    - port: 5000
  selector:
    application: healththree
status:
  loadBalancer: {}
