apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    application: healthzero
  name: healthzero
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        application: healthzero
    spec:
      containers:
        - name: healthone
          image: stekarabdevregistry.azurecr.io/healthzero:v1
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: healthzero
  name: healthzero-service
spec:
  ports:
    - port: 5000
  selector:
    application: healthzero
status:
  loadBalancer: {}
