apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: health2
  name: health2
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        run: health2
    spec:
      containers:
        - name: health2
          image: stekarabdevregistry.azurecr.io/health2:v1
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: health2
  name: health2-service
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    run: health2
status:
  loadBalancer: {}
